baseURL = 'https://ozgurvurgun.github.io/'
languageCode = 'en-us'
title = 'emre.xyz | @delirehberi'
theme="archie"
copyright= "delirehberi"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

params.mode="auto"
 
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ozgurvurgun"

[[params.social]]
name = "Bluesky"
icon = "at-sign"
url = "https://bsky.app/profile/emre.xyz"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://youtube.com/EmreYILMAZ"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/delirehberi"

[[params.social]]
name = "Nostr"
icon = "at-sign"
url = "https://satellite.earth/@delirehberi@emre.xyz"

[[params.social]]
name = "VCF"
icon = "phone"
url = "http://emre.xyz/me.vcf"
[[params.social]]
name = "Resume"
icon = "file-text"
url = "http://emre.xyz/resume.pdf"

[[menu.main]]
name = "main"
url = "/"
weight = 1

[[menu.main]]
name = "gist"
url = "https://gist.github.com/delirehberi"
weight = 2

[[menu.main]]
name = "nostr"
url = "https://nostr.emre.xyz"
weight = 3

[[menu.main]]
name = "til"
url = "/til"
weight = 3 

[[menu.main]]
name = "me"
url = "/about"
weight = 4

[[menu.main]]
name = "subscribe"
url = "/subscribe"
weight = 5

[[menu.main]]
name = "resume"
url = "/resume.pdf"
weight = 6

enableEmoji = true
enableInlineShortcodes = true

[sitemap]
  changefreq = 'weekly'
  priority = 1.0

[markup.goldmark.renderer]
unsafe= true




