baseURL = 'https://ozgurvurgun.github.io/'
languageCode = 'en-us'
title = '@ozgurvurgun'
theme="archie"
copyright= "ozgurvurgun"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

params.mode="auto"
 
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ozgurvurgun"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/ozgurvurgun1"

[[params.social]]
name = "VCF"
icon = "phone"
url = "http://emre.xyz/me.vcf"

[[params.social]]
name = "Resume"
icon = "file-text"
url = "http://emre.xyz/resume.pdf"

[[menu.main]]
name = "main"
url = "/"
weight = 1

[[menu.main]]
name = "gist"
url = "https://gist.github.com/ozgurvurgun"
weight = 2

[[menu.main]]
name = "me"
url = "/about"
weight = 3

enableEmoji = true
enableInlineShortcodes = true

[sitemap]
  changefreq = 'weekly'
  priority = 1.0

[markup.goldmark.renderer]
unsafe= true




